export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const FETCH_LIST_START = 'FETCH_LIST_START';
export const FETCH_ROLE_SUCCESS = 'FETCH_ROLE_SUCCESS';
export const FETCH_POSITION_SUCCESS = 'FETCH_POSITION_SUCCESS';
export const FETCH_LIST_FAIL = 'FETCH_LIST_FAIL';

export const UPDATE_CONFIRMATION = 'UPDATE_CONFIRMATION';

export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';

export const FETCH_ITEMS = 'FETCH_ITEMS';
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const CLEAR_ITEMS = 'CLEAR_ITEMS';

export const PARTS_START = 'PARTS_START';
export const PARTS_SUCCESS = 'PARTS_SUCCESS';
export const PARTS_FAIL = 'PARTS_FAIL';
export const ADD_PART = 'ADD_PART';
export const EDIT_PART = 'EDIT_PART';
export const REMOVE_PART = 'REMOVE_PART';
export const SET_PARTS = 'SET_PARTS';

export const CATEGORIES_START = 'CATEGORIES_START';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
export const CATEGORIES_FAIL = 'CATEGORIES_FAIL';
export const SET_CATEGORIES = 'SET_CATEGORIES';
